---
title: "Post-hoc tests"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(papaja)
```

## Resistance

```{r cars, echo=F, message=F}
### Load data and functions within ####
source("dataPreparation.R")

### weibull for impact on health
summaryDF108mice$impact <- summaryDF108mice$relWL +0.01

## TOLERANCE
summaryDF108mice$ToleranceIndex <- log10(
  summaryDF108mice$relWL / summaryDF108mice$peak.oocysts.per.g.mouse + 1e-8) / (-8)

# by strains
modResStrain <- glm.nb(peak.oocysts.per.g.mouse ~ infection_isolate*Mouse_genotype,
                 data = summaryDF108mice)
anova(modResStrain, test = "LRT")
# SIGNIF infection isolate (p-value = 0.01902) + interactions with mice (p-value = 8.432e-05)

# postHoc test
summaryDF108mice$intFac <- interaction(summaryDF108mice$infection_isolate,
                                       summaryDF108mice$Mouse_genotype, drop=T)

modResStrainformulticomp <- glm.nb(peak.oocysts.per.g.mouse ~ intFac, data = summaryDF108mice)
postHocRes <- summary(glht(modResStrainformulticomp, linfct=mcp(intFac = "Tukey")))

# apa_print(postHocRes)
```
```{r results = 'asis', echo = TRUE}
apa_table(apa_print.summary.glht(postHocRes))
```
